### PR TITLE
Add support for Net 8

### LINKED ISSUE #107: Add support for Net 8
It would be really nice to be able to use this for new/upgraded projects as well :)

### PR DESCRIPTION
**Pull request by pingvinen**
This PR adds support for using the tool with Net 8 projects.

Fixes #107 

## 🛑  STOP 🛑 

The branch for this PR is currently based on the #109 branch!

### CODE REVIEW

**Comment by pingvinen** [comment]
After an - admittedly - very quick look, it seems to me that our current AppVeyor setup does not support dotnet core < 3. I see that we have the #79 issue, which might make sense to get done if AppVeyor will not allow us to build those versions anyway (without changing the setup at least).

What are your thoughts on this @nover?

**Comment by nover** [comment]
Thanks for the PR @pingvinen  :) 

I agree, let's remove support for the deprecated dotnet versions first, bump the appveyor image to get 8.0 support and then we'll release a new major version of the tool.

**Comment by pingvinen** [comment]
> Are you up for fixing that as well?

Yes :)

**Comment by pingvinen** [comment]
This PR seems to be ready as soon as we merge #79 and rebase this branch :)

**Comment by nover** [comment]
#109 is merged and I've just rebased this branch via the GitHub UI. Once CI is passing I'll merge

**Review by nover — APPROVED** [review]

**Comment by haltcase** [comment]
Now that this is merged, what's the expected release timeline? (No pressure, just looking forward to using it with .NET 8 😁)

**Pull request merged**
